### ISSUE TITLE
Theme Encoder Bug: 'CardThemeData' can't be assigned to the parameter type 'CardTheme?'

### ISSUE THREAD

**Issue by oskarbruening** [peiffer-innovations/json_theme#225]
After updating to the latest version (6.5.3+2) and upgrading flutter, I'm getting the following error:

```
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/json_theme-6.5.3+2/lib/src/codec/theme_encoder.dart:7117:44: 
Error: The argument type 'CardThemeData' can't be assigned to the parameter type 'CardTheme?'.
```

```
Flutter 3.26.0-1.0.pre.421 • channel master • https://github.com/flutter/flutter.git
Framework • revision c78c166e3e (2 hours ago) • 2024-10-09 16:15:22 -0400
Engine • revision 3a95d6e1dd
Tools • Dart 3.6.0 (build 3.6.0-334.2.beta) • DevTools 2.40.1
```

[Update] After some more poking around, it seems like it might not be the update of json_theme itself but either the flutter update or the upgrade to Xcode 16.

**Comment by jpeiffer** [comment]
It's related to the new version of Flutter.  Someone's created a PR that looks to address it:

https://github.com/peiffer-innovations/json_theme/pull/229

I'm going to close this issue and suggest any remaining conversation happens via that PR since the version of Flutter you (and that PR) are using have not been released to stable yet.
