### ISSUE TITLE
app crash and examples with deprecated properties

### ISSUE THREAD

**Issue by acx70** [peiffer-innovations/json_theme#27]
It looks like the examples provided with the folder [themes](https://github.com/peiffer-innovations/json_theme/tree/main/example/assets/themes) do not include the latest version of flutter' styles. For example: inside "big_red.json" there is the property "buttonColor" which is deprecated:

```   "buttonColor": "#b71c1c",  ```

If I define the following theme, the app crashes

```
  "buttonTheme": {
    "colorScheme": {
      "background":"#0d47a1"
    }
  },
```

Would it be possible to have an example of "elevatedButton" ?

Versions:
 json_theme: ^3.0.1
 flutter: 2.5.3

Thank you

**Comment by jpeiffer** [comment]
The examples still work (which is intended) and they have the old and the current in there.  The issue with using `colorScheme` is that all attributes are required.  You cannot just define "background" in `ColorSchema`, you have to define them all per Flutter's specifications.
![image](https://user-images.githubusercontent.com/6424555/139970058-d7ad357d-8e4c-4009-be61-4f3392ae04c0.png)

That's why you get this error when you try the above JSON:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      ThemeDecoder.decodeColorScheme (package:json_theme/src/codec/theme_decoder.dart:2193:10)
#1      ThemeDecoder.decodeButtonThemeData (package:json_theme/src/codec/theme_decoder.dart:1733:22)
#2      ThemeDecoder.decodeThemeData (package:json_theme/src/codec/theme_decoder.dart:9464:22)
#3      RootPage._onThemeSelected (package:example/main.dart:42:30)
<asynchronous suspension>
```

So for that one in particular, you just need to define all the required attributes.

Regarding your question about ElevatedButton, I suspect you're in the wrong place.  This repo is really just for ThemeData.  There's a sibling library you may want to look into called: [json_dynamic_widget](https://github.com/peiffer-innovations/json_dynamic_widget/).  It is the one that can parse and render widgets and it uses this one.

A specific example for `elevated_button` can be found in it: [here](https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/buttons.json).

I'm going to close this issue.  Feel free to open a new one if you still have more problems.
