### ISSUE TITLE
Decoding example theme throws CastError exception

### ISSUE THREAD

**Issue by zeshuaro** [peiffer-innovations/json_theme#30]
Using VSCode with "Uncaught Exceptions" turned on, when I try to decode all the example themes in this repo with `ThemeDecoder.decodeThemeData(json)`, it throws the following exception:

```
_CastError (Null check operator used on a null value)
```

I think the exception is actually coming from the underlying package `json_scheme2`, but I'm not sure which part of the code is failing. Would you be able to help look into this?

PS I think the themes are still being decoded properly if we ignore the exception.

_A related issue was raised in https://github.com/zeshuaro/flutter_theme/issues/157_

**Comment by jpeiffer** [comment]
I cannot reproduce this issue via the example in this repo.  I see an issue logged with `flutter_theme`, and the problem may be there.  If you can provide more info on how you are able to reproduce via just the code in this repo, I'd be happy to take another look.

As a FYI, any error coming from `json_schema2` is really a warning rather than an error.  All the entities supported by this repo also come with a Schema file that in debug and profile mode it validates against.  If you're a `Null check...` error from `json_schema2` means that you have a schema defined but it cannot be properly evaluated for some reason.  You can disable the schema validations by setting `SchemaHelper.enabled = false;` at the start of your application, or you can try to diagnose what is wrong with the schema in question.

I'll leave this open for a few days in case you would like to provide more info about how to repro the problem via the example app in this repo.

**Comment by zeshuaro** [comment]
Looks like the issue has been fixed in the latest version `3.2.0`. But it's definitely reproducible with the example app in this repo on `3.1.2+1`. 

With "Uncaught Exceptions" turned on in VSCode:

![image](https://user-images.githubusercontent.com/12210067/145768139-57abbdd1-d86c-4bee-a63a-b6d6e3ef49ed.png)

If you run the example app in this repo and then click on any of the themes, the debugger will pause with the error `_CastError (Null check operator used on a null value)` being raised in `json_schema2`.

![image](https://user-images.githubusercontent.com/12210067/145768415-c2337fce-ce14-41e2-ad05-541c84243ef6.png)

Anyway thanks for the details on the schema validation. Since this issue has somehow been resolved in the latest version, I'll just close this issue and simply use the latest version 🙂
