### ISSUE TITLE
generating theme.dart file

### ISSUE THREAD

**Issue by forumics** [peiffer-innovations/json_theme#67]
upon app start up, 
- get json file
- parse json file
- decode theme
- init theme

this process is heavy and adds to app startup time.
the read json, parse json and decode theme part can be done just once and the generated dart file can be consumed directly instead.

Suggesting to add a function to generate theme.dart file

**Comment by jpeiffer** [comment]
That actually defeats the purpose of this library as this library is intended to allow a theme to be updated via something like an API or a Firestore document rather than built at compile time.

If you want a fully compile time theme, you're probably better off simply writing it in Dart as opposed to trying to code generate it via JSON.  Either way, I personally hate code generators and avoid them whenever possible so this will not be an issue I intend to address.  Pull requests are always welcome though, and if you would like to contribute a generator, I'll consider merging it.
